[package]
name = "platform-wayland"
version.workspace = true
edition.workspace = true

[dependencies]
kime-core = { path = "../kime-core" }
wayland-client = "0.31"
wayland-protocols-wlr = { version = "0.3.12", features = ["client"] }
wayland-protocols-misc = { version = "0.3.12", features = ["client"] }
cosmic-text = "0.19.0"
fontdb = "0.24"
xkbcommon = "0.9"
libc = "0.2"