[package]
name = "kime-core"
version.workspace = true
edition.workspace = true

[dependencies]
rusqlite = { version = "0.40", features = ["bundled"] }
kime-pinyin = { path = "../kime-pinyin" }
kime-shuangpin = { path = "../kime-shuangpin" }
fst = "0.4.7"
memmap2 = "0.9"
anyhow = "1.0.104"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"

[dev-dependencies]
tempfile = "3"